import type { Event } from "./types";

export const eventData: Event[] = [
  {
    id: 1,
    title: "Beach Cleanup Drive",
    organization: "Beach Cleanup Association",
    date: "2026-02-15",
    time: "08:00 - 12:00",
    location: "Ancol Beach, Jakarta",
    category: "Environment",
    image: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&h=400&fit=crop",
    description: "Volunteers will work together to clean plastic waste along Ancol Beach to protect marine ecosystems.",
    requirements: ["Age 15+", "Comfortable shoes", "Sun protection"],
    benefits: ["Certificate", "Lunch provided", "Community service hours"],
  },
  {
    id: 2,
    title: "Mangrove Planting Program",
    organization: "Bumi Lestari Foundation",
    date: "2026-02-20",
    time: "07:30 - 11:30",
    location: "Pantai Indah Kapuk, Jakarta",
    category: "Environment",
    image: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&h=400&fit=crop",
    description: "Help restore coastal ecosystems by planting mangroves with local environmental activists.",
    requirements: ["Physical fitness", "Outdoor clothing"],
    benefits: ["Certificate", "Environmental training"],
  },
  {
    id: 3,
    title: "Free Tutoring for Elementary Students",
    organization: "Bright Future Volunteers",
    date: "2026-02-22",
    time: "13:00 - 16:00",
    location: "Tambora, Jakarta",
    category: "Education",
    image: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=400&fit=crop",
    description: "Assist elementary school students with basic math and reading skills.",
    requirements: ["Patient", "Basic teaching skills"],
    benefits: ["Teaching experience", "Certificate"],
  },
  {
    id: 4,
    title: "Blood Donation Campaign",
    organization: "Red Cross Society",
    date: "2026-02-25",
    time: "09:00 - 14:00",
    location: "Red Cross HQ, Jakarta",
    category: "Health",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=400&fit=crop",
    description: "Support medical staff in organizing and managing a blood donation drive.",
    requirements: ["Age 18+", "Healthy condition"],
    benefits: ["Health check", "Volunteer certificate"],
  },
  {
    id: 5,
    title: "Community Library Management",
    organization: "Book Lovers Club",
    date: "2026-03-01",
    time: "10:00 - 15:00",
    location: "Depok, West Java",
    category: "Education",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&h=400&fit=crop",
    description: "Help organize books and assist visitors at a local community library.",
    requirements: ["Organized", "Love reading"],
    benefits: ["Certificate", "Library access"],
  },

  {
    id: 6,
    title: "Urban Tree Planting",
    organization: "Green City Initiative",
    date: "2026-03-05",
    time: "07:00 - 11:00",
    location: "Bekasi City Park",
    category: "Environment",
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=400&fit=crop",
    description: "Plant trees in urban areas to improve air quality.",
    requirements: ["Outdoor ready"],
    benefits: ["Certificate", "Community points"],
  },
  {
    id: 7,
    title: "Food Distribution for Homeless",
    organization: "Helping Hands NGO",
    date: "2026-03-07",
    time: "16:00 - 20:00",
    location: "Central Jakarta",
    category: "Social",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&h=400&fit=crop",
    description: "Distribute food packages to homeless communities.",
    requirements: ["Empathy", "Teamwork"],
    benefits: ["Certificate", "Meal included"],
  },
  {
    id: 8,
    title: "Tech Workshop for Seniors",
    organization: "Silver Surfers Club",
    date: "2026-03-10",
    time: "09:00 - 12:00",
    location: "Surabaya",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop",
    description: "Teach basic smartphone and internet usage to seniors.",
    requirements: ["Basic IT knowledge"],
    benefits: ["Teaching experience"],
  },
  {
    id: 9,
    title: "Public Health Education Campaign",
    organization: "Health First Foundation",
    date: "2026-03-12",
    time: "08:00 - 13:00",
    location: "Bandung",
    category: "Health",
    image: "https://images.unsplash.com/photo-1584036561584-b03c19da874c?w=800&h=400&fit=crop",
    description: "Educate communities about hygiene and disease prevention.",
    requirements: ["Communication skills"],
    benefits: ["Certificate"],
  },
  {
    id: 10,
    title: "Disaster Relief Logistics Support",
    organization: "Rapid Response Team",
    date: "2026-03-15",
    time: "09:00 - 17:00",
    location: "Semarang",
    category: "Disaster",
    image: "https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800&h=400&fit=crop",
    description: "Assist in sorting and distributing disaster relief supplies.",
    requirements: ["Physical strength"],
    benefits: ["Volunteer hours", "Certificate"],
  },
  {
    id: 11,
    title: "River Cleanup Action",
    organization: "River Guardians Group",
    date: "2026-04-05",
    time: "07:00 - 11:00",
    location: "Ciliwung River, Jakarta",
    category: "Environment",
    image: "https://images.unsplash.com/photo-1508873699372-7aeab60b44b1?w=800&h=400&fit=crop",
    description: "Help clean the Ciliwung River to reduce pollution and improve water quality for nearby communities.",
    requirements: ["Age 16+", "Comfortable clothes", "Willing to get wet"],
    benefits: ["Certificate", "Community service hours", "Snacks provided"],
  },
  {
    id: 12,
    title: "Orphanage Teaching Program",
    organization: "Bright Future Volunteers",
    date: "2026-04-08",
    time: "09:00 - 13:00",
    location: "South Jakarta",
    category: "Education",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&h=400&fit=crop",
    description: "Spend time teaching and mentoring children at a local orphanage through fun learning activities.",
    requirements: ["Patient", "Love working with children"],
    benefits: ["Certificate", "Teaching experience"],
  },
  {
    id: 13,
    title: "Free Medical Check Assistance",
    organization: "Health First Foundation",
    date: "2026-04-10",
    time: "08:00 - 14:00",
    location: "Bogor",
    category: "Health",
    image: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=800&h=400&fit=crop",
    description: "Assist healthcare professionals during a free medical check-up event for residents.",
    requirements: ["Good communication", "Health awareness"],
    benefits: ["Certificate", "Medical exposure"],
  },
  {
    id: 14,
    title: "Food Bank Packing Volunteer",
    organization: "Helping Hands NGO",
    date: "2026-04-12",
    time: "10:00 - 15:00",
    location: "Tangerang",
    category: "Social",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=800&h=400&fit=crop",
    description: "Help pack and distribute food supplies to families in need through the local food bank.",
    requirements: ["Teamwork", "Physical readiness"],
    benefits: ["Certificate", "Lunch provided"],
  },
  {
    id: 15,
    title: "Basic Coding Class for Youth",
    organization: "Doodle Developer Group",
    date: "2026-04-15",
    time: "13:00 - 17:00",
    location: "Yogyakarta",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1515378791036-0648a8148d5e?w=800&h=400&fit=crop",
    description: "Teach basic programming concepts to students interested in technology and software development.",
    requirements: ["Basic programming knowledge"],
    benefits: ["Teaching experience", "Certificate"],
  },
  {
    id: 16,
    title: "Elderly Care Visit Program",
    organization: "Silver Surfers Club",
    date: "2026-04-18",
    time: "09:00 - 12:00",
    location: "Surakarta",
    category: "Social",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=400&fit=crop",
    description: "Spend quality time with elderly residents through conversations and light activities.",
    requirements: ["Empathy", "Friendly attitude"],
    benefits: ["Certificate", "Social impact experience"],
  },
  {
    id: 17,
    title: "School Facility Renovation",
    organization: "Bright Future Volunteers",
    date: "2026-04-20",
    time: "08:00 - 16:00",
    location: "Cirebon",
    category: "Community",
    image: "https://images.unsplash.com/photo-1590650046871-92c887180603?w=800&h=400&fit=crop",
    description: "Assist in repainting and improving school facilities to create a better learning environment.",
    requirements: ["Physical strength", "Team collaboration"],
    benefits: ["Certificate", "Lunch provided"],
  },
  {
    id: 18,
    title: "Waste Sorting Education Campaign",
    organization: "Green City Initiative",
    date: "2026-04-22",
    time: "09:00 - 13:00",
    location: "Denpasar",
    category: "Environment",
    image: "https://images.unsplash.com/photo-1503596476-1c12a8ba09b1?w=800&h=400&fit=crop",
    description: "Educate residents on proper waste sorting and recycling practices.",
    requirements: ["Communication skills"],
    benefits: ["Certificate", "Environmental knowledge"],
  },
  {
    id: 19,
    title: "Mental Health Awareness Seminar",
    organization: "Health First Foundation",
    date: "2026-04-25",
    time: "10:00 - 14:00",
    location: "Malang",
    category: "Health",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=400&fit=crop",
    description: "Support a public seminar focused on raising mental health awareness.",
    requirements: ["Good coordination"],
    benefits: ["Certificate", "Health education"],
  },
  {
    id: 20,
    title: "Community Clean-Up Day",
    organization: "Neighborhood Heroes",
    date: "2026-04-28",
    time: "07:30 - 11:30",
    location: "Makassar",
    category: "Community",
    image: "https://images.unsplash.com/photo-1615484477201-9f4953340fab?w=800&h=400&fit=crop",
    description: "Work together with residents to clean public spaces and strengthen community bonds.",
    requirements: ["Willingness to help"],
    benefits: ["Certificate", "Community engagement"],
  },
];

export const eventService = {
  async getAllEvents(): Promise<Event[]> {
    // const response = await fetch("/api/events");
    // const data = await response.json();
    await new Promise((resolve) => setTimeout(resolve, 500));
    return eventData;
  },
  async getEventById(id: number): Promise<Event | undefined> {
    // const response = await fetch(`/api/events/${id}`);
    // const data = await response.json();
    await new Promise((resolve) => setTimeout(resolve, 300));
    return eventData.find((event) => event.id === id);
  },
};
